import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";
import { Sidebar } from "./components/Sidebar/Sidebar";
import styles from "./page.module.css";
import { Up } from "@/components";

const noto_sans = Noto_Sans({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Rating Project",
  description: "Generated by create next app",
  // openGraph: {
  //   locale: "en_EN",
  // }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <main className={styles.body} role="main">{children}</main>
          <Footer className={styles.footer} />
          <Up/>
        </div>
      </body>
    </html>
  );
}
